# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(default='villager', max_length=10),
        ),
    ]
