# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160416_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winning_team',
            field=models.CharField(blank=True, choices=[('VILLAGER', 'villager'), ('WEREWOLF', 'werewolf')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(choices=[('VILLAGER', 'villager'), ('WEREWOLF', 'werewolf')], default='villager', max_length=10),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('APPRENTICE_SEER', 'apprentice_seer'), ('BODYGUARD', 'bodyguard'), ('CURSED', 'cursed'), ('HUNTER', 'hunter'), ('MASON', 'mason'), ('MAYOR', 'mayor'), ('MINION', 'minion'), ('PRINCE', 'prince'), ('SEER', 'seer'), ('SORCERER', 'sorcerer'), ('TROUBLEMAKER', 'troublemaker'), ('VILLAGER', 'villager'), ('WEREWOLF', 'werewolf'), ('WITCH', 'witch'), ('WOLF_CUB', 'wolf_cub'), ('CUSTOM_NAMES', {'APPRENTICE_SEER': 'Apprentice Seer', 'WOLF_CUB': 'Wolf Cub'})], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='team',
            field=models.CharField(choices=[('VILLAGER', 'villager'), ('WEREWOLF', 'werewolf')], max_length=10),
        ),
        migrations.AlterField(
            model_name='turn',
            name='current_phase',
            field=models.IntegerField(blank=True, choices=[('INITIAL', 0), ('DAY', 1), ('VOTING', 2), ('NIGHT', 3)], default=1, null=True),
        ),
    ]
