# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_modify_choice_enum_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='owner',
        ),
        migrations.AddField(
            model_name='player',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
