# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_turn_is_active_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winning_team',
            field=models.CharField(blank=True, choices=[('villager', 'Villager'), ('werewolf', 'Werewolf')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(choices=[('villager', 'Villager'), ('werewolf', 'Werewolf')], default='villager', max_length=10),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('apprentice_seer', 'Apprentice Seer'), ('bodyguard', 'Bodyguard'), ('cursed', 'Cursed'), ('hunter', 'Hunter'), ('mason', 'Mason'), ('mayor', 'Mayor'), ('minion', 'Minion'), ('prince', 'Prince'), ('seer', 'Seer'), ('sorcerer', 'Sorcerer'), ('troublemaker', 'Troublemaker'), ('villager', 'Villager'), ('werewolf', 'Werewolf'), ('witch', 'Witch'), ('wolf_cub', 'Wolf Cub')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='team',
            field=models.CharField(choices=[('villager', 'Villager'), ('werewolf', 'Werewolf')], max_length=10),
        ),
        migrations.AlterField(
            model_name='turn',
            name='current_phase',
            field=models.IntegerField(blank=True, choices=[(0, 'Initial'), (1, 'Day'), (2, 'Voting'), (3, 'Night')], default=1, null=True),
        ),
    ]
