# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 14:15
from __future__ import unicode_literals

from django.db import migrations, models

from ..models import Role, Roles, Teams


def create_roles(app, schema):
    role_values = {
        Roles.APPRENTICE_SEER: 5,
        Roles.BODYGUARD: 2,
        Roles.CURSED: -1,
        Roles.HUNTER: 1,
        Roles.MASON: 3,
        Roles.MAYOR: 1,
        Roles.MINION: 3,
        Roles.PRINCE: 3,
        Roles.SEER: 8,
        Roles.SORCERER: 5,
        Roles.TROUBLEMAKER: -5,
        Roles.VILLAGER: 0,
        Roles.WEREWOLF: -6,
        Roles.WITCH: 1,
        Roles.WOLF_CUB: -2,
    }

    role_counts = {
        Roles.WEREWOLF: 4,
        Roles.VILLAGER: None,
    }

    role_teams = {
        Roles.WEREWOLF: Teams.WEREWOLF.value,
        Roles.WOLF_CUB: Teams.WEREWOLF.value,
    }

    for role in Roles:
        Role.objects.create(
            role=role.value,
            name=Roles.get_choice_label(role.name),
            team=role_teams.get(role, Teams.VILLAGER.value),
            max_count=role_counts.get(role, 1),
            value=role_values.get(role)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_fix_choice_enum'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='max_count',
            field=models.PositiveSmallIntegerField(
                null=True, blank=True, default=1
            ),
        ),
        migrations.AddField(
            model_name='role',
            name='value',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.RunPython(create_roles),
    ]
