# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_default_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='targets', to='api.Action')),
                ('hut', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Hut')),
                ('player', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Player')),
            ],
        ),
    ]
