# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_actiontarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='hut',
            name='is_visited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hut',
            name='resident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hut', to='api.Resident'),
        ),
    ]
